-- Full migration for the unified services hub. Run once in Supabase's
-- SQL editor. Pure additions — nothing existing (checks_balance, clients,
-- submissions, etc.) is touched, so this is safe to run against the live
-- database with zero risk to what's already working.
--
-- No stored functions here on purpose — the codebase does balance math
-- in JS via conditional PATCH + retry (see api/db.js's
-- atomicAdjustBalance and the new api/_lib/wallet.js), so this migration
-- just adds the columns/tables that pattern operates on.

-- ── Unified wallet ──────────────────────────────────────────────────
alter table clients add column if not exists diamonds numeric(12,2) not null default 0;

create table if not exists diamond_transactions (
  id bigint generated always as identity primary key,
  client_id bigint not null references clients(id),
  amount numeric(12,2) not null,
  note text,
  reference text,
  created_at timestamptz not null default now()
);
create index if not exists diamond_tx_client_id_idx on diamond_transactions (client_id);

-- ── SMS service ─────────────────────────────────────────────────────
create table if not exists sms_services (
  code text primary key,
  name text not null,
  emoji text,
  logo_slug text,
  category text,
  icon_source text,
  updated_at timestamptz not null default now()
);

create table if not exists sms_countries (
  code text primary key,
  name text not null,
  flag text,
  updated_at timestamptz not null default now()
);

create table if not exists sms_holds (
  id text primary key,             -- = order id, generated by the client-side/API caller
  client_id bigint not null references clients(id),
  amount numeric(12,2) not null,
  status text not null default 'held', -- held | finalized | released
  created_at timestamptz not null default now()
);
create index if not exists sms_holds_client_id_idx on sms_holds (client_id);

create table if not exists sms_orders (
  id text primary key,
  pvapins_id text,
  client_id bigint not null references clients(id),
  service_code text not null,
  country_code text not null,
  cost_usd numeric(12,4),
  cost_local numeric(12,2),
  sell_price numeric(12,2),
  phone_number text,
  otp_code text,
  status text not null default 'pending', -- pending | active | completed | expired | cancelled
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sms_orders_client_id_idx on sms_orders (client_id);

create table if not exists sms_rentals (
  id text primary key,
  client_id bigint not null references clients(id),
  service_code text not null,
  country_code text not null,
  days integer not null,
  cost_local numeric(12,2) not null,
  pvapins_deduct numeric(12,4),
  phone_number text,
  received_message boolean not null default false,
  status text not null default 'active', -- active | released | expired
  expiry timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sms_rentals_client_id_idx on sms_rentals (client_id);

-- ── Writing / Rewriting service ─────────────────────────────────────
create table if not exists writing_orders (
  id text primary key,
  client_id bigint not null references clients(id),
  kind text not null,              -- writing | rewriting
  category text not null,          -- technical | non_technical
  instructions text not null,
  pages integer not null,
  price numeric(12,2) not null,
  whatsapp_country_code text not null,
  whatsapp_number text not null,
  attachments jsonb not null default '[]', -- [{name, url}]
  status text not null default 'new',      -- new | files_received | in_progress | completed | delivered
  admin_notes text,
  deliverable_url text,
  worker_id bigint references workers(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists writing_orders_client_id_idx on writing_orders (client_id);
